bids/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # my bids
    path('', views.my_bids),
    # make a bid
    path('make_bid', views.make_bid),
    # checkout
    path('checkout_phase1', views.checkout_phase1),
    path('checkout_phase2', views.checkout_phase2),
    path('checkout_phase3', views.checkout_phase3),

]

item/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # create_item
    path('create_item/<int:id>', views.create_item, name="item-create_item"),
    # my bids
    path('my_bids/<int:id>', views.my_bids, name="item-my_bids"),
    # my listings
    #path('my_listings/<int:id>', views.my_listings, name="item-my_listings"),
    # make a bid
    path('make_bid/<int:id>', views.make_bid, name="item-make_bid"),

    path('<int:id>', views.get_item_by_id, name="item-get_item_by_id"),

    path('delete_item/<int:id>', views.delete_item, name="item-delete_item"),

    path('update_item/<int:id>', views.update_item, name="item-update_item"),

    path('categories/<int:id>', views.categories, name="item-categories"),

    path('delete_bid/<int:id>', views.delete_bid, name='item-delete_bid'),

    path('accept_bid/<int:id>', views.accept_bid, name='item-accept_bid')

    #path('sort_by', views.sort_by, name='item-sort_by')

]

verklegt2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # http://localhost:8000/admin/*
    path('admin/', admin.site.urls),
    # http://localhost:8000/general/*
    path('', include('fire_sale.urls')),
    # user
    path('user/', include('user.urls')),
    # item
    path('item/', include('item.urls')),
    # checkout
    path('checkout/', include('checkout.urls')),

]

item/models.py
from django.contrib.auth.models import User
from django.db import models
# from user.models import User

class ItemCategory(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Item(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=9999, default="")
    description = models.CharField(max_length=255, default="")
    condition = models.CharField(max_length=9999, default="")
    category = models.ForeignKey(ItemCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name




class Bid(models.Model):
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.FloatField(default=0)
    status = models.CharField(max_length=9999, default="pending")


#class AcceptedBids(models.Model):
#    bid = models.ForeignKey(Bid, on_delete=models.CASCADE())
#    status = models.CharField(max_length=9999, default="pending")


class Images(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    image = models.CharField(max_length=9999, default="")

item/forms/item_form.py
from django.forms import ModelForm, widgets
from django import forms
from item.models import Item

class ItemUpdateForm(ModelForm):
    class Meta:
        model = Item
        exclude = ['id', 'seller']
        widgets = {
            'name': widgets.TextInput(attrs={'class': 'form-control'}),
            'condition': widgets.TextInput(attrs={'class': 'form-control'}),
            'description': widgets.TextInput(attrs={'class': 'form-control'}),
            'category': widgets.Select(attrs={'class': 'form-control'})
        }

class ItemCreateForm(ModelForm):
    image = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Item
        exclude = ['id', 'seller']
        widgets = {
            'name': widgets.TextInput(attrs={'class': 'form-control'}),
            'condition': widgets.TextInput(attrs={'class': 'form-control'}),
            'description': widgets.TextInput(attrs={'class': 'form-control'}),
            'category': widgets.Select(attrs={'class': 'form-control'})
        }

item/forms/new_bid_form.py
from django.forms import ModelForm, widgets
from item.models import Bid


class NewBidForm(ModelForm):
    class Meta:
        model = Bid
        exclude = ['id', 'status', 'buyer', 'item']
        widgets = {
            'amount': widgets.TextInput(attrs={'class':'form-control'})
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

import user
from item.forms.item_form import ItemCreateForm, ItemUpdateForm
from item.forms.new_bid_form import NewBidForm
from item.models import Item, Images, ItemCategory, Bid
from django.contrib.auth.models import User
from checkout.models import Rating

# my bids
@login_required
def my_bids(request, id):
    listings = Item.objects.filter(seller__id=id)
    bids = Bid.objects.filter(buyer__id=id)
    ratings = Rating.objects.filter(seller__id=request.user.id).all()
    all_ratings = []
    for i in ratings:
        all_ratings.append(i.rating)
    if len(all_ratings) != 0:
        average_rating = round(sum(all_ratings)/len(all_ratings), 1)
    else:
        average_rating = ""
    highest_bid = []
    all_listings = []
    all_bids_id = []
    all_bid_items = []
    my_listed_items_with_bids = []
    every_bid = []
    for y in Bid.objects.filter(buyer__id=id).all():
        every_bid.append(y)
    new_list = []
    for b in listings:
        for a in Bid.objects.filter(item__id=b.id):
            new_list.append(a)
            my_listed_items_with_bids.append(Item.objects.filter(pk=b.id).first())

    if len(highest_bid) != 0:
        highest_bid_offer = max(highest_bid)
    else:
        highest_bid_offer = ""

    for i in listings:
        all_listings.append(i)

    for j in bids:
        all_bids_id.append(j)

    for bid_bid in all_bids_id:
        item = Item.objects.filter(pk=bid_bid.item.id).first()
        all_bid_items.append(item)
    bid_status = Bid.objects.filter(buyer__id=request.user.id)
    notification = 'False'
    for i in bid_status:
        if i.status == "accepted":
            notification = 'True'
    return render(request, 'item/my_bids.html', {
        'id': id,
        'listings': listings,
        'bid_items': all_bid_items,
        'my_listed_items_with_bids': my_listed_items_with_bids,
        'every_bid': every_bid,
        'new_list': new_list,
        'average_rating': average_rating,
        'notification': notification
    })


# make_bid
@login_required
def make_bid(request, id):
    bid_item = Item.objects.filter(pk=id).first()
    seller = User.objects.filter(pk=bid_item.seller.id).first()
    bid = Bid.objects.filter(item__id=id).all()
    if request.method == 'POST':
        form = NewBidForm(data=request.POST)
        if form.is_valid():
            new_bid = form.save(commit=False)
            new_bid.buyer = request.user
            new_bid.item = bid_item
            new_bid.save()
            return redirect('item-my_bids', request.user.id)
    highest_bid = []
    for i in bid:
        highest_bid.append(i.amount)
    if len(highest_bid) != 0:
        highest_bid_amount = '$' + str(max(highest_bid))
    else:
        highest_bid_amount = 'No bids made'
    ratings = Rating.objects.filter(seller__id=request.user.id).all()
    all_ratings = []
    for i in ratings:
        all_ratings.append(i.rating)
    if len(all_ratings) != 0:
        average_rating = round(sum(all_ratings)/len(all_ratings), 1)
    else:
        average_rating = ""
    bid_status = Bid.objects.filter(buyer__id=request.user.id)
    notification = 'False'
    for i in bid_status:
        if i.status == "accepted":
            notification = 'True'
    return render(request, 'item/make_bid.html', {
        'form': NewBidForm(),
        'bid_item': bid_item,
        'id': id,
        'seller': seller,
        'full_name': seller.profile.first_name + ' ' + seller.profile.last_name,
        'bio': seller.profile.bio,
        'highest_bid': highest_bid_amount,
        'average_rating': average_rating,
        'notification': notification
    })


@login_required
def get_item_by_id(request, id):
    item = Item.objects.filter(pk=id).first()
    seller = User.objects.filter(pk=item.seller.id).first()
    category = item.category
    bid = Bid.objects.filter(item__id=item.id).all()
    ratings = Rating.objects.filter(seller__id=seller.id).all()
    all_ratings = []
    highest_bid = []
    for i in bid:
        highest_bid.append(i.amount)
    if len(highest_bid) != 0:
        highest_bid_amount = '$' + str(max(highest_bid))
    else:
        highest_bid_amount = 'No bids made'
    list_of_items = []
    for i in Item.objects.filter(category__id=category.id).all():
        if i.id != id:
            list_of_items.append(i)

    ratings_user = Rating.objects.filter(seller__id=request.user.id).all()
    all_ratings_user = []
    for i in ratings_user:
        all_ratings_user.append(i.rating)
    if len(all_ratings_user) != 0:
        average_rating = round(sum(all_ratings_user)/len(all_ratings_user), 1)
    else:
        average_rating = ""

    for i in ratings:
        all_ratings.append(i.rating)
    if len(all_ratings) != 0:
        average_rating_seller = round(sum(all_ratings)/len(all_ratings), 1)
    else:
        average_rating_seller = ""
    bid_status = Bid.objects.filter(buyer__id=request.user.id)
    notification = 'False'
    for i in bid_status:
        if i.status == "accepted":
            notification = 'True'
    return render(request, 'item/item.html', {
        'item': item,
        'seller': seller,
        'full_name': seller.profile.first_name + ' ' + seller.profile.last_name,
        'category': category,
        'similar_items': list_of_items,
        'highest_bid': highest_bid_amount,
        'average_rating_seller': average_rating_seller,
        'average_rating': average_rating,
        'notification': notification
    })



@login_required
def create_item(request, id):
    seller = User.objects.filter(pk=id).first()
    ratings = Rating.objects.filter(seller__id=request.user.id).all()
    all_ratings = []
    for i in ratings:
        all_ratings.append(i.rating)
    if len(all_ratings) != 0:
        average_rating = round(sum(all_ratings)/len(all_ratings), 1)
    else:
        average_rating = ""
    if request.method == "POST":
        form = ItemCreateForm(data=request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.seller = request.user
            item.save()
            item_image = Images(image=request.POST['image'], item=item)
            item_image.save()
            return redirect('fire_sale-home_page')
    else:
        form = ItemCreateForm()
        # TODO: Instance new ItemCreateForm()
    bid_status = Bid.objects.filter(buyer__id=request.user.id)
    notification = 'False'
    for i in bid_status:
        if i.status == "accepted":
            notification = 'True'
    return render(request, 'item/create_item.html', {
        'form': form,
        'user.id': seller,
        'average_rating': average_rating,
        'notification': notification
    })

@login_required
def delete_item(request, id):
    item = get_object_or_404(Item, pk=id)
    item.delete()
    return redirect('fire_sale-home_page')


@login_required
def delete_bid(request, id):
    bid = get_object_or_404(Bid, item__id=id)
    bid.delete()
    return redirect('fire_sale-home_page')


@login_required
def accept_bid(request, id):
    bid = get_object_or_404(Bid, item__id=id)
    bid.status = 'accepted'
    bid.save()
    return redirect('fire_sale-home_page')



@login_required
def update_item(request, id):
    instance = get_object_or_404(Item, pk=id)
    ratings = Rating.objects.filter(seller__id=request.user.id).all()
    all_ratings = []
    for i in ratings:
        all_ratings.append(i.rating)
    if len(all_ratings) != 0:
        average_rating = round(sum(all_ratings) / len(all_ratings), 1)
    else:
        average_rating = ""
    if request.method == "POST":
        form = ItemUpdateForm(data=request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('fire_sale-home_page')
    else:
        form = ItemUpdateForm(instance=instance)
    bid_status = Bid.objects.filter(buyer__id=request.user.id)
    notification = 'False'
    for i in bid_status:
        if i.status == "accepted":
            notification = 'True'
    return render(request, 'item/update_item.html', {
        'form': form,
        'id': id,
        'average_rating': average_rating,
        'notification': notification
    })

@login_required
def categories(request, id):
    context = ItemCategory.objects.filter(pk=id).first()
    list_of_items = []
    for i in Item.objects.filter(category__id=id).all():
        list_of_items.append(i)
    ratings = Rating.objects.filter(seller__id=request.user.id).all()
    all_ratings = []
    for i in ratings:
        all_ratings.append(i.rating)
    if len(all_ratings) != 0:
        average_rating = round(sum(all_ratings)/len(all_ratings), 1)
    else:
        average_rating = ""
    bid_status = Bid.objects.filter(buyer__id=request.user.id)
    notification = 'False'
    for i in bid_status:
        if i.status == "accepted":
            notification = 'True'
    return render(request, 'item/categories.html', {
        'id': id,
        'context': context,
        'items': list_of_items,
        'average_rating': average_rating,
        'notification': notification
    })

templates/item/categories.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <div>
            <h1 class="bigHeader">{{ context }}</h1>
            <div id="items_for_sale">
                <div class="allItems">
                    {% for item in items %}
                        {% include 'fire_sale/single_item.html'%}
                    {% endfor %}
                </div>
            </div>

        </div>
    </div>
{% endblock %}

templates/item/create_item.html
{% extends 'base.html' %}

{% block content %}
    <div class="blueBox">
        <div class="blueBoxBar">
            <p class="blueBoxHeader">Create new listing</p>
        </div>
        <form class="blueBoxForm" action="{% url 'item-create_item' user.id %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="blueBoxButton" value="CREATE LISTING"/>
        </form>
    </div>

{% endblock %}

templates/item/item.html
{% extends 'base.html' %}

{% block content %}
    <h1 id="item_title">{{ item.name }}</h1>
    <div class="itemPage">
        <div class="imgItemBox">
            {% for item_image in item.images_set.all %}
                <img class="itemImgBig" src="{{ item_image.image }}" />
            {% endfor %}
        </div>
        <div class="productInfoBox">
            <h2>Product information</h2>
            <div class="productInfo">
                <p><b>Condition: </b>{{ item.condition }}</p>
                <p><b>Description: </b>{{ item.description }}</p>
                <p><b>Category: </b>{{ item.category }}</p>
            </div>
            <div id="highest_bid_box">
                <p id="highest_bid_text">Highest bid: {{ highest_bid }}</p>
            </div>
            <div class="largeButton">
                <button class="makeBidButton"><a href="{% url 'item-make_bid' item.id %}">MAKE A BID</a></button>
            </div>
        </div>
        <div class="sellerInfoBox">
            <h2>Seller information</h2>
            <div class="seller">
                <div id="img_seller">
                    <img class="itemImgSeller" src="{{ seller.profile.profile_picture }}" />
                </div>
                <div class="sellerInfo">
                    <p><b>Name: </b>{{ full_name }}</p>
                    <p><b>Average rating: </b>{{ average_rating_seller }}</p>
                </div>
            </div>
        </div>
        <div class="similarItemsBox">
            <h5>Similar Items</h5>
            {% for item in similar_items %}
                <div class="similarItems">
                    <a class="similarItem" href="/item/{{ item.id }}">
                        <img class="simItemImg" src="{{ item.images_set.first.image }}" />
                        <p class="simItemName"> {{ item.name }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>



{% endblock %}

templates/item/make_bid.html
{% extends 'base.html' %}


{% block content %}
    <h2 class="bigHeader"> {{ bid_item.name }} </h2>
    <div class=makeBidInfo>
        <div class="makeBidImgBox">
            <img class="itemImg" src="{{ bid_item.images_set.first.image }}" />
        </div>
        <div class="makeBidInfoProduct">
            <div id=description_product>
                <h3><b>Description of the product</b></h3>
                <p>{{ bid_item.description }}</p>
            </div>
            <div id=information_seller>
                <h3><b>Information on seller</b></h3>
                <p><b>Name:</b> {{ full_name }}</p>
                <p><b>Bio:</b> {{ bio }}</p>
            </div>
            <div id="highest_bid">
                <h4 id="highest_bid_text">Highest bid: {{ highest_bid }}</h4>
            </div>
        </div>
        <div class="makeNewBid">
            <h2><b>New bid</b></h2>
            <p id="not_info">You will get notified in 'My listings' if your bid is accepted</p>
            <div id="bid_amounts">
                <p>Please write your offer in <u>dollars ($):</u></p>
                <form method="post" class="form form-horizontal">
                    {% csrf_token %}
                    {{ form }}
                <input type="submit" class="makeBidButton" value="SUBMIT" />
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/item/my_bids.html
{% extends 'base.html' %}

{% block content %}
    <div class="myBidsOver">
        <div class="myBids1">
            <h2 class="bigHeader">My listed items</h2>
            <h6 class="bigHeader">All items I have for sale</h6>
                {% for i in listings %}
                    <div class="each_bid_div">
                        <div class="each_bid_div_left">
                            <a href="{% url 'item-get_item_by_id' i.id %}">
                                <h4 class="each_bid_header">{{ i }}</h4>
                                <img class="listingImage1" src="{{i.images_set.first.image}}"/>
                            </a>
                        </div>
                        <div class="editItemButtonsDiv1">
                            <a href="{% url 'item-delete_item' i.id %}" class="delUpdateButtons">Delete</a>
                            <a href="{% url 'item-update_item' i.id %}" class="delUpdateButtons">Update</a>
                        </div>
                    </div>
                {% endfor %}
        </div>


        <div class="myBids2">
            <h2 class="bigHeader">Bids on my items</h2>
            <h6 class="bigHeader">Bids on the items I have for sale</h6>
                {% for i in my_listed_items_with_bids %}
                    <div class="each_bid_div2">
                        <div class="each_bid_div_left">
                            <a href="{% url 'item-get_item_by_id' i.id %}">
                                <h4 class="each_bid_header">{{ i }}</h4>
                                <img class="listingImage2" src="{{i.images_set.first.image}}"/>
                            </a>
                        </div>
                        <div class="each_listing_div_right">
                            <div id="each_listing_div_right_top">
                                {% for k in new_list %}
                                    {% if k.item_id == i.id %}
                                        <h4>Bid amount: {{ k.amount }}</h4>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            {% for y in new_list %}
                               {% if i.id == y.item_id %}
                                    {% if y.status == 'pending' %}
                                        <div class="editItemButtonsDiv">
                                            <a href="{% url 'item-delete_bid' i.id %}" class="decOfferButton">Decline offer</a>
                                            <a href="{% url 'item-accept_bid' i.id %}" class="accOfferButton">Accept offer</a>
                                        </div>
                                    {% else %}
                                        <h5>PENDING</h5>
                                        <P>Waiting for <u>buyer</u> to purchase the item</P>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                         </div>
                    </div>
                {% endfor %}
        </div>
        <div class="myBids3">
            <h2 class="bigHeader">My bids</h2>
            <h6 class="bigHeader">All bids I have made</h6>
                {% for item in bid_items %}
                    <div class="each_bid_div2">
                        <div class="each_bid_div_left">
                            <a href="{% url 'item-get_item_by_id' item.id %}">
                                <h4 class="each_bid_header">{{ item }}</h4>
                                <img class="listingImage3" src="{{item.images_set.first.image}}"/>
                            </a>
                        </div>
                        <div class="each_bid_div_right">
                            <div id="each_listing_div_right_top">
                                {% for y in every_bid %}
                                    {% if item.id == y.item_id %}
                                        {% if y.status == 'accepted' %}
                                            <div id="offer_bid_box">
                                                <h5>Your offer has been accepted!</h5>
                                                <p id="offer_bid_text">Offer: {{ y.amount }}</p>
                                            </div>
                                            <div id="accepted_bids">
                                                <button id=accept_button><a href="{% url 'checkout-checkout_phase1' item.id %}">Purchase</a></button>
                                            </div>
                                        {% else %}
                                            <div class="pending_bid3">
                                                <h5>PENDING</h5>
                                                <P>Waiting for <u>seller</u> to accept the offer</P>
                                            </div>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
        </div>
    </div>

{% endblock %}

templates/item/my_listings.html
{% extends "base.html" %}
{% block content %}
    <h1>{{ item.name }}</h1>
    <a href="{% url 'item-delete_item' item.id %}" class="block btn btn-primary">Delete item</a>
    <a href="{% url 'item-update_item' item.id %}" class="block btn btn-primary">Update item</a>
{% endblock %}

templates/item/sort_by.html
{% extends 'base.html' %}

{% block content %}

        <h1 class="bigHeader">{{ context.name }}</h1>
        <div id="items_for_sale">
            <div class="allItems">
                {% for item in context %}
                    {% include 'fire_sale/single_item.html'%}
                {% endfor %}
            </div>
        </div>

{% endblock %}

templates/item/update_item.html
{% extends 'base.html' %}

{% block content %}
    <div class="blueBox">
        <div class="blueBoxBar">
            <p class="blueBoxHeader">Update item</p>
        </div>
        <form class="blueBoxForm" action="{% url 'item-update_item' id %}" method="post">
        {% csrf_token %}
        {{ form }}
            <input type="submit" class="blueBoxButton" value="UPDATE LISTING"/>
        </form>
    </div>
{% endblock %}